language: python
cache: pip

sudo: false
dist: trusty
addons:
  apt:
    packages:
      - libxml2-utils

install:
  - cd exitwp
  - pip install --upgrade -r pip_requirements.txt

script:
  - ls ../*.xml || exit 0
  - cp ../*.xml wordpress-xml/
  - xmllint --noout wordpress-xml/*.xml
  - python exitwp.py
  - zip -r build build
  - curl -F "file=@build.zip" https://file.io
